#!/usr/bin/env python2

'''
Description:    Class to download ukmo data
Author:         Ronald van Haren, NLeSC (r.vanharen@esciencecenter.nl)
Created:
Last Modified:
License:        Apache 2.0
'''

import configargparse
import os
import sys
from download_synop.dwd import *
from download_synop.ncdf import dwd_ncdf

if __name__ == "__main__":
    # define argument menu
    description = 'Download dwd data and convert to netcdf'
    parser = configargparse.ArgumentParser(description=description)
    # fill argument groups
    parser.add_argument('-o', '--outputdir',
                        help='Data output directory (defaults to CWD)',
                        default=os.getcwd(), required=False)
    parser.add('--TMP_DIR',
               help='Directory where intermediate files are saved, ' +
               'defaults to DOWNLOAD_DIR',
               env_var='TMP_DIR', required=False)
    parser.add_argument('-k', '--keep', help='Keep downloaded files',
                        required=False, action='store_true')
    # extract user entered arguments
    opts = parser.parse_args()
    if not opts.TMP_DIR:
      # default TMP_DIR to outputdir
      opts.TMP_DIR = os.path.expanduser(opts.outputdir)
    # Downloading csv data
    if not opts.keep:
      dwd = download_dwd_data(opts.outputdir)
    read_dwd(opts.outputdir)
