#!/usr/bin/env python2

'''
Description:    Class to download knmi data
Author:         Ronald van Haren, NLeSC (r.vanharen@esciencecenter.nl)
Created:
Last Modified:
License:        Apache 2.0
'''

import configargparse
import os
import sys
from download_synop.knmi import *
from download_synop.ncdf import knmi_ncdf

if __name__ == "__main__":
    # define argument menu
    description = 'Get data KNMI reference stations'
    parser = argparse.ArgumentParser(description=description)
    # fill argument groups
    parser.add_argument('-o', '--outputdir', help='Data output directory',
                        default=os.path.join(os.getcwd(),'KNMI'),
                        required=False)
    parser.add_argument('-s', '--stationid', help='Station id',
                        default='', required=False, action='store')
    parser.add_argument('-k', '--keep', help='Keep downloaded files',
                        required=False, action='store_true')
    # extract user entered arguments
    opts = parser.parse_args()
    # process data
    get_knmi_reference_data(opts)
    load_knmi_data(filename)
